\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{res}[7/1/2015 Estilo de Respostas]
\LoadClass[
	a4paper,
	10pt,
	% twocolumn,
	]{article}

%\RequirePackage{titlesec}

\usepackage{
	setspace,
	enumerate,
	url,
	lmodern,
	multicol,
	% ulem,
	indentfirst,
	graphicx,
	}

\usepackage[
	colorlinks,
	linkcolor=blue,
	]{hyperref}

\usepackage[
	brazil
	]{babel}

\usepackage[
	utf8
	]{inputenc}

\usepackage[
	bottom=2cm,
	top=3cm,
	left=3cm,
	right=2cm
	]{geometry}

%\usepackage[
%	b5
%	]{crop}

\usepackage[
	T1
	]{fontenc}

%\onehalfspacing
\date{Data da revisão: \today{}}
\author{Fábio Rodrigues Ribeiro}
%\renewcommand*{\familydefault}{\sfdefault}
%\setlength{\parskip}
%\setlength{\parident}

%\usepackage{fancyhdr}
%\pagestyle{fancy}
%\fancyhf{}
%\rhead{}
%\lhead{}
%\cfoot{\thepage}
