set nocompatible

syntax on "Coloração do texto para salvar arquivo
set textwidth=80 "Comprimento da linha
set background=dark "Cores para fundo preto
set fenc=utf8 "Define enconding do arquivo
set enc=utf8 "Define encoding do texto
set fileformat=unix "Formato de arquivo unix
set backupext=.bak "Extensão do aquivo de backup
set backupdir=~/.vim/bk/ "Determina local do backup
set ai! " Força Identação automática
set nu
set ignorecase
set smartcase
"set smarttab
set is
set hls "Highlight para busca
set magic "Força regex
set lbr! "Na visualização força a quebra de linha
"set cindent

" code completation HTML
iab html_doc <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
iab html_char <META http-equiv="Content-Type" content="text/html; charset=utf-8">
iab linux GNU/Linux
iab html_autor <META name="author" content="Fábio Rodrigues Ribeiro">
iab latex_author \author{Fábio Rodrigues Ribeiro}
iab html_css <LINK rel="stylesheet" type="text/css" title="Padrão" href="">

" Fecha chaves, colchetes e parentes automaticamente
imap { {}<left>
imap ( ()<left>
imap [ []<left>
imap < <><left>

set spelllang=pt "Dicionário em Português
map <F3> <ESC>:set spell<CR>

"Atalho para salvar arquivo
map <F2> <ESC>:w<CR>

"Chama .vimrc
map <F12> <ESC>:e ~/.vimrc<CR>

"Recarrega .vimrc
map <F5> <ESC>:source ~/.vimrc<CR>

"Ativa syntax txt2tags
au BufNewFile,BufRead *.t2t set ft=txt2tags 

"Regex
"Primeira letra maiúscula
map <F9> <ESC>:%s/[.!?]\_s\+\a/\U&\E/gc<CR>

"Limpa espaço em branco no fim da linha
map <F8> <ESC>:%s/ \+$//gc
