syntax on "Coloração do texto
set spelllang=pt "Dicionário em Portugues
set background=dark "Cores para fundo preto
set fenc=utf8 "Define enconding do arquivo
set enc=utf8 "Define encoding do texto
set fileformat=unix "Formato de arquivo unix
set backupext=.bak 
set ai!
set nu
set ignorecase
set smartcase
set is
set lbr!
"set cindent

" code completation HTML
iab html_doc <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
iab html_char <META http-equiv="Content-Type" content="text/html; charset=utf-8">
iab linux GNU/Linux
iab html_autor <META name="author" content="Fábio Rodrigues Ribeiro">
iab latex_author \author{Fábio Rodrigues Ribeiro}
iab html_css <LINK rel="stylesheet" type="text/css" title="Padrão" href="">

" Fecha chaves, colchetes e parentes automaticamente
imap { {}<left>
imap ( ()<left>
imap [ []<left>
imap < <><left>
