\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{res}[7/1/2015 estilo de Respostas]
\LoadClass[a4paper, 12pt, twocolumn]{article}
%\RequirePackage{titlesec}
\usepackage{setspace,enumerate,url,lmodern, textcomp}
\usepackage[brazil]{babel}
\usepackage[utf8]{inputenc}
\usepackage[bottom=2cm,top=3cm,left=2cm,right=2cm]{geometry}
%\usepackage[b5]{crop}
\usepackage[T1]{fontenc}
\onehalfspacing
\date{Data da revisão: \today{}}
\author{Fábio Rodrigues Ribeiro}
%\renewcommand*{\familydefault}{\sfdefault}
%\setlength{\parindent}{3cm}
%\setlength{\parskip}{0.5cm}
